### ISSUE TITLE
Citations don't show up on SB page

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/slim-data-release-template#12]
Larger citations and cross-citations from metadata don't show up on SB page. Perhaps they should show up in Related External Resources like they do in this model archive: https://www.sciencebase.gov/catalog/item/606b30ecd34edc0435c3662b, but open to suggestions.

Solution should be applied as a PR to this template and to Simon's model archive repo: https://github.com/SimonTopp/drb_generalizability_data_release

Issue raised by @SimonTopp

**Comment by amsnyder** [comment]
@SimonTopp - I looked at a few other data releases and model archives. They typically don't seem to have citations to other related work on the page, but I see that this model archive does: https://www.sciencebase.gov/catalog/item/606b30ecd34edc0435c3662b.

Do you want to add some citations as Related External Resources to your archive? Is it all of your citations that you want to add, or just some specific ones?

**Comment by SimonTopp** [comment]
Honestly I'm pretty impartial.  My take on it is that either it should be removed from the template if it doesn't propagate through to the the release or it should propagate through and show up in `Related External Resources`.  I think it's more a matter of defining what we think needs to be included in a data release.  There aren't many in mine, but it's not an insignificant task to type out a bunch of citations if they only ever exist in the git repo and don't end up being public facing. Does that make sense?  Is there guidance anywhere on if they need to be included?

**Comment by amsnyder** [comment]
Oh they are still a part of the metadata.xml file, which is a required part of the release. The metadata.xml file populates a large portion of the SB landing page by default to make your life easier (you don't have to go and fill in a bunch of similar information twice) - but there is not a 1:1 mapping between everything in the metadata.xml and the SB landing page fields. A user has to look through that metadata.xml to get a lot of the required metadata information (like entity and attributes - where you define you files and the fields in them). It's unfortunate that so much of the metadata is only in the xml file - which is a frustrating file format to work with, but that's the system we are working with for now.

All that being said, if there are any specific citations that you really would like to highlight on the landing page so that a user can easily see them, we can surely find a way to add them (either manually or with the pipeline)

**Comment by SimonTopp** [comment]
Derp! I'm seeing that now.  I looked over the xml before I sent the last message but must have glossed over it.  Maybe one way to clear this up would be comment out the templates to show what maps to what (i.e. "Metadata xml", "SB Related External Resources").  That way there's a clearer understanding from the user side, and it would help identify bugs like "Data Format" showing up in "External Resources".  I'm personally fine without the citations mapping to the actual landing page, so I'll defer to you two if that's worth adding.

**Comment by amsnyder** [comment]
I think we are both a bit overcommitted right now, so I don't think we'll add the citation piece to the template or write up the mapping of fields right now, but we will consider it if we get time in the future! This is a feature of SB, not the pipeline. I just looked and SB doesn't seem to indicate the mapping either - they just say that it automatically populates the SB page and leave it at that.
