### ISSUE TITLE
`sb_replace_files_log()` does not exist

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/slim-data-release-template#21]
It is the function referenced by the final target, `log/sb_posted_files.csv`. I think it can be safely replaced by `sb_replace_files()`

**Comment by amsnyder** [comment]
@msleckman - do you have this function somewhere? could you add it to `src/sb_utils`

**Comment by amsnyder** [comment]
@lindsayplatt - this function has been added to this repo
